# Generated by Django 2.1.1 on 2018-09-17 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journalapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=150)),
                ('amount_eaten', models.IntegerField()),
                ('time_eaten', models.DateTimeField()),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journalapi.User')),
            ],
        ),
    ]
