# Generated by Django 2.1.4 on 2018-12-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapi', '0002_foodentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_id', models.IntegerField()),
            ],
        ),
    ]
