language: python
python:
  - "3.6"
install:
  - pip install -r travis/requirements.txt
script:
  - python manage.py test

services: postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

addons:
  postgresql: "9.4"
